-- MariaDB Test Data Initialization
-- Creates tables with test data for data-absorb

USE testdb;

DROP TABLE IF EXISTS all_types;
DROP TABLE IF EXISTS nullable_test;
DROP TABLE IF EXISTS huge_table;

CREATE TABLE all_types (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_smallint SMALLINT,
    col_float FLOAT,
    col_double DOUBLE,
    col_decimal DECIMAL(18,4),
    col_varchar VARCHAR(500),
    col_text TEXT,
    col_bool BOOLEAN,
    col_date DATE,
    col_timestamp DATETIME,
    col_blob BLOB
) ENGINE=InnoDB;

SET SESSION foreign_key_checks = 0;
SET SESSION unique_checks = 0;

INSERT INTO all_types VALUES 
(1, 100, 1000000, 50, 1.5, 2.5, 123.45, 'test', 'test text', true, '2024-01-01', '2024-01-01 10:00:00', NULL),
(2, 200, 2000000, 100, 3.5, 4.5, 456.78, 'test2', 'test2 text', false, '2024-01-02', '2024-01-02 11:00:00', NULL),
(3, 300, 3000000, 150, 5.5, 6.5, 789.12, 'test3', 'test3 text', true, '2024-01-03', '2024-01-03 12:00:00', NULL),
(4, 400, 4000000, 200, 7.5, 8.5, 111.11, 'test4', 'test4 text', false, '2024-01-04', '2024-01-04 13:00:00', NULL),
(5, 500, 5000000, 250, 9.5, 10.5, 222.22, 'test5', 'test5 text', true, '2024-01-05', '2024-01-05 14:00:00', NULL);

INSERT INTO all_types (id, col_int, col_bigint, col_smallint, col_float, col_double, col_decimal, col_varchar, col_text, col_bool, col_date, col_timestamp)
SELECT 
    n + 6,
    (n + 6) % 100000,
    (n + 6) * 1000,
    (n + 6) % 1000,
    (n + 6) * 0.123456789,
    (n + 6) * 1.23456789,
    (n + 6) * 1.2345,
    CONCAT('varchar_', n + 6),
    CONCAT('text_', n + 6),
    (n + 6) % 2 = 0,
    DATE_ADD('2024-01-01', INTERVAL ((n + 6) % 365) DAY),
    TIMESTAMPADD(MINUTE, (n + 6) % 100000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
    LIMIT 995
) nums;

CREATE TABLE nullable_test (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_varchar VARCHAR(200),
    col_decimal DECIMAL(10,2),
    col_timestamp DATETIME,
    col_bool BOOLEAN
);

INSERT INTO nullable_test VALUES 
(1, 100, 'test1', 100.50, '2024-01-01 10:00:00', true),
(2, NULL, NULL, NULL, NULL, NULL),
(3, 300, 'test3', 300.75, '2024-01-03 12:00:00', false),
(4, NULL, 'test4', 400.00, '2024-01-04 13:00:00', true),
(5, 500, NULL, NULL, '2024-01-05 14:00:00', false);

CREATE TABLE huge_table (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    value DECIMAL(15,2),
    flag BOOLEAN,
    created_at DATETIME
);

INSERT INTO huge_table (id, name, value, flag, created_at)
SELECT 
    n,
    CONCAT('name_', LPAD(n, 7, '0')),
    n * 0.01,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 100000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + e.N * 10000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
    LIMIT 100000
) nums;

CREATE TABLE export_table_1 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_1
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_2 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_2
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_3 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_3
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_4 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_4
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_5 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_5
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_6 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_6
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_7 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_7
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_8 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_8
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_9 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_9
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_10 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_10
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_11 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_11
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_12 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_12
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_13 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_13
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_14 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_14
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_15 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_15
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_16 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_16
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_17 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_17
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_18 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_18
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_19 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_19
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

CREATE TABLE export_table_20 (
    id BIGINT PRIMARY KEY,
    col_int INT,
    col_bigint BIGINT,
    col_varchar VARCHAR(100),
    col_decimal DECIMAL(10,2),
    col_bool BOOLEAN,
    created_at DATETIME
);

INSERT INTO export_table_20
SELECT 
    n,
    n * 1,
    n * 1000,
    CONCAT('text_', n),
    n * 1.5,
    n % 2 = 0,
    TIMESTAMPADD(MINUTE, n % 10000, '2024-01-01 00:00:00')
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + 1 as n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
    LIMIT 10000
) nums;

SELECT 'all_types' as table_name, COUNT(*) as row_count FROM all_types
UNION ALL
SELECT 'nullable_test', COUNT(*) FROM nullable_test
UNION ALL
SELECT 'huge_table', COUNT(*) FROM huge_table
UNION ALL
SELECT 'export_table_1', COUNT(*) FROM export_table_1
UNION ALL
SELECT 'export_table_20', COUNT(*) FROM export_table_20;